# APT Full Profile
# 完整配置 - 启用所有功能和最大性能

profile:
  name: full
  description: "完整配置，启用所有高级特性和最大性能"
  version: "2.0.0"

model:
  # 模型架构选择
  architecture: apt_xlarge
  hidden_size: 4096
  num_layers: 48
  num_attention_heads: 64
  intermediate_size: 16384
  max_position_embeddings: 8192
  vocab_size: 150000

  # 功能开关（全部启用）
  features:
    multimodal: true
    moe: true
    num_experts: 16
    experts_per_token: 2
    flash_attention: true
    gradient_checkpointing: true
    sparse_attention: true
    adaptive_computation: true

training:
  # 训练配置
  batch_size: 128
  gradient_accumulation_steps: 16
  learning_rate: 1.5e-5
  warmup_steps: 5000
  max_steps: 1000000

  # 分布式训练
  distributed:
    enabled: true
    backend: nccl
    world_size: 64
    pipeline_parallel: 4
    tensor_parallel: 4
    data_parallel: 4
    expert_parallel: 4
    sequence_parallel: true

  # 混合精度
  mixed_precision: bf16
  fp8_training: true

  # 优化器
  optimizer: adamw_fused
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8
  gradient_clipping: 1.0

memory:
  # 内存优化（激进策略）
  offload_optimizer: true
  cpu_offload: true
  max_memory_per_gpu: "80GB"
  gradient_checkpointing: true
  activation_checkpointing: full
  offload_activations: true
  zero_stage: 3

vgpu:
  # Virtual Blackwell配置（全功能）
  enabled: true
  max_virtual_gpus: 64
  scheduling: adaptive
  isolation: true
  memory_pooling: true
  dynamic_allocation: true
  multi_instance: true

perf:
  # 性能优化（最大化）
  compile_model: true
  use_torch_compile: true
  inductor_config:
    max_autotune: true
    shape_padding: true
    aggressive_fusion: true
  profile_enabled: true
  profile_interval: 500
  kernel_fusion: true
  graph_optimization: true

extensions:
  # 扩展功能（全部启用）
  rag:
    enabled: true
    index_type: faiss_gpu_multi
    embedding_dim: 4096
    top_k: 20
    multi_index: true
  knowledge_graph:
    enabled: true
    backend: neo4j_cluster
    cache_size: 100000
    distributed: true
  mcp:
    enabled: true
    protocol_version: "1.0"
    max_contexts: 1000
    distributed: true
  graph_rag:
    enabled: true
    hop_limit: 3

plugins:
  # 插件配置（启用所有）
  enabled:
    - custom_metrics
    - data_augmentation
    - advanced_logging
    - model_profiling
    - custom_callbacks
    - experiment_tracking
    - auto_tuning

monitoring:
  # 监控配置（完整监控）
  tensorboard: true
  wandb: true
  mlflow: true
  prometheus: true
  metrics_interval: 5
  log_gradients: true
  log_parameters: true
  log_activations: true
  system_monitoring: true
  gpu_monitoring: true
  network_monitoring: true

checkpoints:
  # 检查点配置（高频率保存）
  save_interval: 100
  keep_last_n: 20
  save_optimizer: true
  async_save: true
  sharded_checkpoints: true
  cloud_backup: true
  incremental_save: true

security:
  # 安全配置
  encryption: true
  checkpoint_signing: true
  secure_communication: true

data:
  # 数据配置
  num_workers: 16
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true

inference:
  # 推理优化
  speculative_decoding: true
  quantization: int8
  dynamic_batching: true
  tensor_parallel_inference: true
