# APT Pro Profile
# 专业配置 - 适用于大规模训练和高性能场景

profile:
  name: pro
  description: "专业配置，针对大规模训练优化"
  version: "2.0.0"

model:
  # 模型架构选择
  architecture: apt_large
  hidden_size: 2048
  num_layers: 32
  num_attention_heads: 32
  intermediate_size: 8192
  max_position_embeddings: 4096
  vocab_size: 100000

  # 功能开关
  features:
    multimodal: true
    moe: true
    num_experts: 8
    experts_per_token: 2
    flash_attention: true
    gradient_checkpointing: true

training:
  # 训练配置
  batch_size: 64
  gradient_accumulation_steps: 8
  learning_rate: 2.0e-5
  warmup_steps: 2000
  max_steps: 500000

  # 分布式训练
  distributed:
    enabled: true
    backend: nccl
    world_size: 16
    pipeline_parallel: 2
    tensor_parallel: 2
    data_parallel: 4

  # 混合精度
  mixed_precision: bf16
  fp8_training: false

  # 优化器
  optimizer: adamw_fused
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-8

memory:
  # 内存优化
  offload_optimizer: true
  cpu_offload: false
  max_memory_per_gpu: "80GB"
  gradient_checkpointing: true
  activation_checkpointing: selective

vgpu:
  # Virtual Blackwell配置
  enabled: true
  max_virtual_gpus: 16
  scheduling: priority
  isolation: true
  memory_pooling: true

perf:
  # 性能优化
  compile_model: true
  use_torch_compile: true
  inductor_config:
    max_autotune: true
    shape_padding: true
  profile_enabled: true
  profile_interval: 1000

extensions:
  # 扩展功能
  rag:
    enabled: true
    index_type: faiss_gpu
    embedding_dim: 2048
    top_k: 10
  knowledge_graph:
    enabled: true
    backend: neo4j
    cache_size: 10000
  mcp:
    enabled: true
    protocol_version: "1.0"
    max_contexts: 100

plugins:
  # 插件配置
  enabled:
    - custom_metrics
    - data_augmentation
    - advanced_logging
    - model_profiling

monitoring:
  # 监控配置
  tensorboard: true
  wandb: true
  mlflow: true
  metrics_interval: 10
  log_gradients: true
  log_parameters: true
  system_monitoring: true

checkpoints:
  # 检查点配置
  save_interval: 250
  keep_last_n: 10
  save_optimizer: true
  async_save: true
  sharded_checkpoints: true
