# APT Tiny Debug Profile
# 最小配置，用于快速验证和冒烟测试

name: "tiny_debug"
version: "1.0.0"
description: "最小配置用于调试，不启用任何插件"

# 不启用插件（纯核心）
plugins: []

# 最小模型配置
model:
  d_model: 64
  num_heads: 4
  num_layers: 2
  d_ff: 256
  vocab_size: 256
  max_seq_len: 128

  # 使用默认注意力
  attention_name: tva_default

  # 简化的TVA参数
  tva:
    r: 2
    s: 1
    tau: 0.2

# 快速训练配置
training:
  batch_size: 2
  max_epochs: 3
  learning_rate: 1e-4
  warmup_steps: 10
  weight_decay: 0.01
  gradient_clip: 1.0

  mixed_precision: false
  save_freq: 1
  checkpoint_dir: "./checkpoints/tiny_debug"

# 无调度（立即启用）
schedules: {}

# 简单数据
data:
  train_path: "./apt_model/train.txt"
  val_path: "./apt_model/train.txt"  # 复用训练数据
  loader: "text_default"
  max_length: 128

# 基础评估
evaluation:
  metrics: ["perplexity"]
  eval_freq: 10
  save_best: false

# CPU模式
hardware:
  device: "cpu"
  num_gpus: 0
  distributed: false

# 详细调试
debug:
  verbose: true
  log_level: "DEBUG"
  profile_memory: true
  check_gradients: true
