# APT Model 全局配置文件
# 这些设置会在每次运行时自动加载，无需每次指定命令行参数

# Debug模式设置
debug:
  enabled: false              # 是否启用Debug模式 (true/false)
  log_level: INFO            # 日志级别: DEBUG, INFO, WARNING, ERROR
  profile_memory: false      # 是否进行内存分析
  check_gradients: false     # 是否检查梯度
  save_debug_logs: true      # 是否保存详细的debug日志文件

# 默认训练参数
training:
  default_epochs: 20
  default_batch_size: 8
  default_learning_rate: 3.0e-5
  checkpoint_auto_save: true

# 分词器设置
tokenizer:
  auto_detect_language: true
  cache_tokenizer: true

# 日志设置
logging:
  colored_output: true       # 是否使用彩色日志输出
  log_to_file: true         # 是否同时输出到文件
  log_directory: "apt_model/log"

# 设备设置
hardware:
  auto_gpu: true            # 自动使用GPU（如果可用）
  mixed_precision: false    # 混合精度训练

# 其他设置
misc:
  language: zh_CN           # 默认界面语言 (zh_CN, en_US)
  auto_backup: false        # 自动备份检查点
